// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktnqkzrujwyfhzlpxfxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bnFrenJ1and5Zmh6bHB4ZnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzI4MDgsImV4cCI6MjA2NTIwODgwOH0.qXhloiHz6NkY3UNnpwSuhsIufliVkdjLqsOwWwOTxW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);